service: quizifer-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-south-1
  memorySize: 512

functions:
  app:
    handler: index.handler
    events: 
      - http: 
          path: /qotd
          method: ANY
          cors: true
      - http:
          path: /auth/github
          method: GET
          cors: true
      - http: 
          path: /auth/github/callback
          method: GET
          cors: true
      - http: 
          path: /me
          method: GET
          cors: true
      - http: 
          path: /bookmarks/{bookmark}
          method: ANY
          cors: true
      - http: 
          path: /stats/{event}
          method: PUT
          cors: true
    
custom:
  warmup:
    appWarmer:
      enabled: true
      events:
        - schedule: rate(5 minutes)

plugins:
  - serverless-offline
  - serverless-plugin-warmup
