service: quizifer-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  memorySize: 512

functions:
  app:
    handler: index.handler
    events: 
      - http: 
          path: /qotd
          method: ANY
          cors: true
      - http: 
          path: /stats/{event}
          method: PUT
          cors: true
      
plugins:
  - serverless-offline
  - serverless-plugin-warmup
