service: quizifer-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  memorySize: 512

functions:
  app:
    handler: index.handler
    events: 
      - http: 
          path: /qotd
          method: ANY
          cors: true
      - http: 
          path: /auth/github
          method: GET
          cors: true
      - http: 
          path: /auth/github/callback
          method: GET
          cors: true
      - http: 
          path: /me
          method: GET
          cors: true
      
plugins:
  - serverless-offline
